#FROM maven:3.8.4-openjdk-17-slim AS build
#WORKDIR /app
#COPY . /app
#RUN --mount=type=cache,id=s/90ecd4c0-aeee-4981-928a-39fdd8c184f1-m2/repository,target=/root/.m2/repository chmod +x ./mvnw && ./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install
#
#FROM openjdk:17-slim
#WORKDIR /app
#COPY --from=build /app/target/*.jar app.jar
#EXPOSE 8080
#CMD ["java", "-jar", "app.jar"]
FROM adoptopenjdk:17-jdk-hotspot

WORKDIR /app

COPY target/bookingT-0.0.1-SNAPSHOT.jar /app/railwayProject.jar

EXPOSE 8080

CMD ["java", "-jar", "railwayProject"]
